# Generated by Django 4.0.1 on 2024-09-11 09:31

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0004_entry_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32, null=True),
        ),
    ]
