# Generated by Django 4.0.1 on 2024-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KwentasApp', '0007_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
