name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - master  # Change this to your main branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Change this to match your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare for Deployment
      run: |
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput

    - name: Deploy to PythonAnywhere
      env:
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PYTHONANYWHERE_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        PYTHONANYWHERE_APP_NAME: ${{ secrets.PYTHONANYWHERE_APP_NAME }}
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_APP_NAME }}/reload/ -H "Authorization: Token $API_TOKEN")
        echo "Reload response: $RESPONSE"
