name: Deploy Django to PythonAnywhere

on:
  push:
    branches:
      - master  # Change this to your main branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Change this to match your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare for Deployment
      run: |
        python manage.py collectstatic --noinput
        python manage.py migrate --noinput

    - name: Deploy to PythonAnywhere
      env:  # Define environment variables
        API_TOKEN: ${{ '5b7f14b1f4e0b1229c4d9f98a16c4d4e36efe36d' }}  # Use the secret here
        PYTHONANYWHERE_USERNAME: ${{ 'KwentasKlarasPMIS' }}  # Use your PythonAnywhere username
        PYTHONANYWHERE_APP_NAME: ${{ 'KwentasKlarasPMIS' }}  # Use your app name
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ env.PYTHONANYWHERE_USERNAME }}/webapps/${{ env.PYTHONANYWHERE_APP_NAME }}/reload/ \
        -H "Authorization: Token $API_TOKEN"
